<a href="https://colab.research.google.com/github/Hussainaquib/R-programs/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Write R code to create a 3x3 matrix filled with the values 1 to 9, using the matrix() function. Then extract the first row and last column of the matrix using row and column indexing.**

In [ ]:
m=matrix(1:9,nrow=3,ncol=3)
print(m)
print(m[1,])
print(m[,3])

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] 1 4 7
[1] 7 8 9


**Define a 4x4 matrix with all elements set to 0, and then fill the diagonal with the values 1, 2, 3, and 4 using the diag()**

In [ ]:
m= matrix(0:0,nrow=4,ncol=4)
diag(m)<-c(1,2,3,4)
print(m)

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    2    0    0
[3,]    0    0    3    0
[4,]    0    0    0    4


**Create two matrices, A and B, each with dimensions 3x3, filled with random values. Combine them into a single matrix C by binding them together by columns**

In [ ]:
A<-matrix(seq(1,4),nrow=2,ncol=2,byrow=TRUE)
B<-matrix(seq(5,8),nrow=2,ncol=2,byrow=TRUE)
C<-cbind(A,B)
print(C)

     [,1] [,2] [,3] [,4]
[1,]    1    2    5    6
[2,]    3    4    7    8


**Define a 5x5 matrix and replace the values in the 3rd row and 4th column with the value 0, using indexing**

In [ ]:
m5=matrix(1:25,nrow=5,ncol=5)
m5[3,4]<-0
print(m5)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13    0   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25


**2x2 matrix with any values you choose, and then extract the elements in the top-right and bottom-left positions using the indexing operator**

In [ ]:
x<-matrix(1:4,nrow=2,ncol=2)
print(x[1,2])
print(x[2,1])

[1] 3
[1] 2


**Create a three dimensional array with six layer of a 4X2 matrix , filled with decreasing sequence of values between 4.8 to 0.1 of appropriate length**

In [ ]:
seq<-seq(0.1, 4.8 ,by = 0.1)
sort<-sort(seq,decreasing = TRUE)
matrix<- array(sort,dim=c(4,2,6))
print(matrix)

, , 1

     [,1] [,2]
[1,]  4.8  4.4
[2,]  4.7  4.3
[3,]  4.6  4.2
[4,]  4.5  4.1

, , 2

     [,1] [,2]
[1,]  4.0  3.6
[2,]  3.9  3.5
[3,]  3.8  3.4
[4,]  3.7  3.3

, , 3

     [,1] [,2]
[1,]  3.2  2.8
[2,]  3.1  2.7
[3,]  3.0  2.6
[4,]  2.9  2.5

, , 4

     [,1] [,2]
[1,]  2.4  2.0
[2,]  2.3  1.9
[3,]  2.2  1.8
[4,]  2.1  1.7

, , 5

     [,1] [,2]
[1,]  1.6  1.2
[2,]  1.5  1.1
[3,]  1.4  1.0
[4,]  1.3  0.9

, , 6

     [,1] [,2]
[1,]  0.8  0.4
[2,]  0.7  0.3
[3,]  0.6  0.2
[4,]  0.5  0.1



**Extract and store as a new object the fourth and first row elements in that order , of the second column only of all layers of previous question**

In [ ]:
seq<-seq(0.1, 4.8 ,by = 0.1)
sort<-sort(seq,decreasing = TRUE)
matrix<- array(sort,dim=c(4,2,6))
Extract <-matrix[c(1,4),2 , ]
print(Extract)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]  4.4  3.6  2.8  2.0  1.2  0.4
[2,]  4.1  3.3  2.5  1.7  0.9  0.1


**Use a fourfold repetition of the second row of matrix formed in previous question to fill a new array of dimensions 2X2X2**

In [ ]:
seq<-seq(0.1, 4.8 ,by = 0.1)
sort<-sort(seq,decreasing = TRUE)
matrix<- array(sort,dim=c(4,2,6))
Extract <-matrix[c(1,4),2 , ]
a= rep(Extract[2, ],4)
new= array(a,dim =c(2,2,2))
print(new)

, , 1

     [,1] [,2]
[1,]  4.1  2.5
[2,]  3.3  1.7

, , 2

     [,1] [,2]
[1,]  0.9  4.1
[2,]  0.1  3.3



**Create a new array comprised of the results of deleting the sixth layer**

In [ ]:
seq<-seq(0.1, 4.8 ,by = 0.1)
sort<-sort(seq,decreasing = TRUE)
matrix<- array(sort,dim=c(4,2,6))
extract <-matrix[ , ,-6]
print(extract)

, , 1

     [,1] [,2]
[1,]  4.8  4.4
[2,]  4.7  4.3
[3,]  4.6  4.2
[4,]  4.5  4.1

, , 2

     [,1] [,2]
[1,]  4.0  3.6
[2,]  3.9  3.5
[3,]  3.8  3.4
[4,]  3.7  3.3

, , 3

     [,1] [,2]
[1,]  3.2  2.8
[2,]  3.1  2.7
[3,]  3.0  2.6
[4,]  2.9  2.5

, , 4

     [,1] [,2]
[1,]  2.4  2.0
[2,]  2.3  1.9
[3,]  2.2  1.8
[4,]  2.1  1.7

, , 5

     [,1] [,2]
[1,]  1.6  1.2
[2,]  1.5  1.1
[3,]  1.4  1.0
[4,]  1.3  0.9



**Overwrite the second and fourth row elements of the second column of layers 1,3 and 5 of previous question with -99**

In [ ]:
seq<-seq(0.1, 4.8 ,by = 0.1)
sort<-sort(seq,decreasing = TRUE)
matrix<- array(sort,dim=c(4,2,6))
matrix[c(2,4),2,c(1,3,5)]<- -99
print(matrix)


, , 1

     [,1]  [,2]
[1,]  4.8   4.4
[2,]  4.7 -99.0
[3,]  4.6   4.2
[4,]  4.5 -99.0

, , 2

     [,1] [,2]
[1,]  4.0  3.6
[2,]  3.9  3.5
[3,]  3.8  3.4
[4,]  3.7  3.3

, , 3

     [,1]  [,2]
[1,]  3.2   2.8
[2,]  3.1 -99.0
[3,]  3.0   2.6
[4,]  2.9 -99.0

, , 4

     [,1] [,2]
[1,]  2.4  2.0
[2,]  2.3  1.9
[3,]  2.2  1.8
[4,]  2.1  1.7

, , 5

     [,1]  [,2]
[1,]  1.6   1.2
[2,]  1.5 -99.0
[3,]  1.4   1.0
[4,]  1.3 -99.0

, , 6

     [,1] [,2]
[1,]  0.8  0.4
[2,]  0.7  0.3
[3,]  0.6  0.2
[4,]  0.5  0.1

